<?php

function register_fields_article() {

	if( function_exists('acf_add_local_field_group') ):

		acf_add_local_field_group(array (
			'key' => 'group_5a02fffb35a17',
			'title' => 'Article Content',
			'fields' => array (
				array (
					'key'   => 'article_tab',
					'label' => __( 'Article Content'),
					'name'  => 'article_tab',
					'type'  => 'tab',
				),
				// array (
				// 	'key' => 'field_598c58e23b24f',
				// 	'label' => 'Article Image',
				// 	'name' => 'article_image',
				// 	'type' => 'image',
				// 	'instructions' => '',
				// 	'required' => 0,
				// 	'conditional_logic' => 0,
				// 	'wrapper' => array (
				// 		'width' => '',
				// 		'class' => '',
				// 		'id' => '',
				// 	),
				// 	'preview_size' => 'medium',
				// 	'library' => 'all',
				// 	'return_format' => 'array',
				// 	'min_width' => 0,
				// 	'min_height' => 0,
				// 	'min_size' => 0,
				// 	'max_width' => 0,
				// 	'max_height' => 0,
				// 	'max_size' => 0,
				// 	'mime_types' => '',
				// ),
				array (
					'key' => 'field_59ac3a13fb09e',
					'label' => 'Article Quote',
					'name' => 'article_quote',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 0,
					'tabs' => 'all',
					'delay' => 0,
				),
// array (
// 	'key' => 'article_top_content',
// 	'label' => 'Article Top Content',
// 	'name' => 'article_top_content',
// 	'type' => 'wysiwyg',
// 	'instructions' => '',
// 	'required' => 1,
// 	'conditional_logic' => 0,
// 	'wrapper' => array (
// 		'width' => '',
// 		'class' => '',
// 		'id' => '',
// 	),
// 	'default_value' => '',
// 	'toolbar' => 'full',
// 	'media_upload' => 1,
// 	'tabs' => 'all',
// 	'delay' => 0,
// ),
				array (
					'key' => 'field_59aa22616ed33',
					'label' => 'Article  Content',
					'name' => 'article_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 1,
					'tabs' => 'all',
					'delay' => 0,
				),
				array (
					'key' => 'field_598ef9246325d',
					'label' => 'Article Summary',
					'name' => 'article_summary',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
				array (
					'key' => 'field_59aa3a8ab424c',
					'label' => 'Article Tag',
					'name' => 'article_tag',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'post_tag',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'load_save_terms' => 0,
					'return_format' => 'object',
					'multiple' => 0,
					'add_term' => 1,
					'load_terms' => 0,
					'save_terms' => 0,
				),
				array (
					'key' => 'field_59aa20439ea3d',
					'label' => 'Featured Article',
					'name' => 'featured_article',
					'type' => 'true_false',
					'instructions' => 'Lastet 3 featured articles will be displayed at main page.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
// array (
// 	'key' => 'field_598c59473b250',
// 	'label' => 'Article Ad Banner',
// 	'name' => 'ad_banner',
// 	'type' => 'image',
// 	'instructions' => 'Upload ad banner which will be displayed at article page.',
// 	'required' => 0,
// 	'conditional_logic' => 0,
// 	'wrapper' => array (
// 		'width' => '',
// 		'class' => '',
// 		'id' => '',
// 	),
// 	'preview_size' => 'thumbnail',
// 	'library' => 'uploadedTo',
// 	'return_format' => 'array',
// 	'min_width' => 0,
// 	'min_height' => 0,
// 	'min_size' => 0,
// 	'max_width' => 0,
// 	'max_height' => 0,
// 	'max_size' => 0,
// 	'mime_types' => '',
// ),
				array (
					'key' => 'field_59b68aaa59ff3',
					'label' => 'Relevant Companies',
					'name' => 'relevant_companies',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'object',
					'post_type' => array (
						0 => 'company',
					),
					'taxonomy' => array (
					),
					'filters' => array (
						0 => 'search',
					),
					'max' => 10,
					'min' => 0,
					'elements' => array (
						0 => 'post_type',
					),
				),
				array (
					'key' => 'field_59b68bed59ff5',
					'label' => 'Featured Interviews',
					'name' => 'featured_interviews',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'object',
					'post_type' => array (
						0 => 'interview',
					),
					'taxonomy' => array (
					),
					'filters' => array (
						0 => 'search',
					),
					'max' => 4,
					'min' => 0,
					'elements' => array (
						0 => 'post_type',
					),
				),
//				array (
//					'key'   => 'advertising_tab',
//					'label' => __( 'Advertising'),
//					'name'  => 'advertising_tab',
//					'type'  => 'tab',
//				),
//				array (
//					'key' => 'article_advertising',
//					'label' => 'advertising',
//					'name' => 'article_advertising',
//					'type' => 'relationship',
//					'instructions' => '',
//					'required' => 0,
//					'conditional_logic' => 0,
//					'wrapper' => array (
//						'width' => '',
//						'class' => '',
//						'id' => '',
//					),
//					'return_format' => 'object',
//					'post_type' => array (
//						0 => 'advertising',
//					),
//					'taxonomy' => array (
//					),
//					'filters' => array (
//						0 => 'search',
//					),
//					'max' => 1,
//					'min' => 0,
//					'elements' => array (
//						0 => 'post_type',
//					),
//				),
//				array (
//					'key'   => 'video_tab',
//					'label' => __( 'Background video'),
//					'name'  => 'avideo_tab',
//					'type'  => 'tab',
//				),
//				array (
//					'key' => 'background_video_file',
//					'label' => 'Background video (MP4)',
//					'name' => 'background_video_file',
//					'type' => 'file',
//					'instructions' => '',
//					'required' => 0,
//					'conditional_logic' => 0,
//					'wrapper' => array (
//						'width' => '',
//						'class' => '',
//						'id' => '',
//					),
//					'return_format' => 'url',
//					'library' => 'all',
//					'min_size' => '',
//					'max_size' => '',
//					'mime_types' => '',
//				),
//				array (
//					'key' => 'background_video_file_2',
//					'label' => 'Background video (webm)',
//					'name' => 'background_video_file_2',
//					'type' => 'file',
//					'instructions' => '',
//					'required' => 0,
//					'conditional_logic' => 0,
//					'wrapper' => array (
//						'width' => '',
//						'class' => '',
//						'id' => '',
//					),
//					'return_format' => 'url',
//					'library' => 'all',
//					'min_size' => '',
//					'max_size' => '',
//					'mime_types' => '',
//				),
			),
'location' => array (
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'article',
		),
	),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'active' => 1,
'description' => '',
));

endif;
}
add_action( 'init', 'register_fields_article' );