<?php

function register_fields_interview()
{
    if (function_exists('acf_add_local_field_group')):

        acf_add_local_field_group(array(
            'key' => 'group_5a02fffb54f9b',
            'title' => 'Interview Posts',
            'fields' => array(
                array(
                    'key' => 'field_598d46c30738e',
                    'label' => 'Image',
                    'name' => 'upload_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'return_format' => 'array',
                    'min_width' => 0,
                    'min_height' => 0,
                    'min_size' => 0,
                    'max_width' => 0,
                    'max_height' => 0,
                    'max_size' => 0,
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_595636d44208a',
                    'label' => 'Designation',
                    'name' => 'ceo_position',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_598d488e4e7fa',
                    'label' => 'Associated Company',
                    'name' => 'company',
                    'type' => 'relationship',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'object',
                    'post_type' => array(
                        0 => 'company',
                    ),
                    'taxonomy' => array(),
                    'filters' => array(
                        0 => 'search',
                    ),
                    'max' => 1,
                    'min' => 0,
                    'elements' => array(
                        0 => 'post_type',
                    ),
                ),
                array(
                    'key' => 'field_59b384ae4dabb',
                    'label' => 'Associated Company',
                    'name' => 'associated_company_text',
                    'type' => 'text',
                    'instructions' => 'If the Company is not listed in above List, Mention It here',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
//                array (
//                    'key' => 'field_59b23ea87052a',
//                    'label' => 'Sector',
//                    'name' => 'sector',
//                    'type' => 'taxonomy',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array (
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'taxonomy' => 'post_tag',
//                    'field_type' => 'select',
//                    'allow_null' => 0,
//                    'load_save_terms' => 0,
//                    'return_format' => 'id',
//                    'multiple' => 0,
//                    'add_term' => 1,
//                    'load_terms' => 0,
//                    'save_terms' => 0,
//                ),
                array(
                    'key' => 'field_5956375ae6d59',
                    'label' => 'Body',
                    'name' => 'body',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'tabs' => 'all',
                    'delay' => 0,
                ),
                // array (
                // 	'key' => 'field_599186ceb7311',
                // 	'label' => 'The Excerpt',
                // 	'name' => 'the_excerpt',
                // 	'type' => 'textarea',
                // 	'instructions' => '',
                // 	'required' => 0,
                // 	'conditional_logic' => 0,
                // 	'wrapper' => array (
                // 		'width' => '',
                // 		'class' => '',
                // 		'id' => '',
                // 	),
                // 	'default_value' => '',
                // 	'placeholder' => '',
                // 	'maxlength' => '',
                // 	'rows' => '',
                // 	'new_lines' => 'br',
                // ),
                array(
                    'key' => 'field_59941e84c03c9',
                    'label' => 'Context Story',
                    'name' => 'context_story',
                    'type' => 'relationship',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'object',
                    'post_type' => array(
                        0 => 'article',
                    ),
                    'taxonomy' => array(),
                    'filters' => array(
                        0 => 'search',
                    ),
                    'max' => '',
                    'min' => 0,
                    'elements' => array(
                        0 => 'post_type',
                    ),
                ),
                array(
                    'key' => 'field_59aa3d6f12338',
                    'label' => 'Featured Interview',
                    'name' => 'featured_interview',
                    'type' => 'true_falseув',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'interview',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(),
            'active' => 1,
            'description' => '',
        ));

    endif;
}

add_action('init', 'register_fields_interview');